[pytest]
addopts = --alluredir=./reports/allure-results

# Agregar la opción del chrome driver path
#chrome_driver_path = ../chromedriver.exe
#chrome_driver_path = C:/Users/lclar/Documents/space-shine-automation/chromedriver.exe